a1piVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  namespace: {{ .Values.meshctrlplanens }}
spec:
  istio:
    global:
      controlPlaneSecurityEnabled: {{ .Values.meshinstall.controlPlaneSecurityEnabled }}
      disablePolicyChecks: {{ .Values.meshinstall.disablePolicyChecks }}
      mtls:
        enabled: {{ .Values.meshinstall.mtls }}
      proxy:
        accessLogFile: {{ .Values.meshinstall.accessLogFile }}
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: {{ .Values.meshinstall.rewriteAppHTTPProbe }}
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
    mixer:
      policy:
        autoscaleEnabled: false
      telemetry:
        autoscaleEnabled: false
    pilot:
      autoscaleEnabled: false
      traceSampling: 100
    kiali:
      enabled: {{ .Values.meshinstall.kiali }}
    grafana:
      enabled: {{ .Values.meshinstall.grafana }}
    tracing:
      enabled: {{ .Values.meshinstall.tracing }}
      jaeger:
        template: {{ .Values.meshinstall.jaegertemplate }}
