apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
spec:
  channel: {{ .Values.elasticchannel }}
  installPlanApproval: {{ .Values.installplanapproval }}
  name: kiali-ossm
  source: {{ .Values.rhoperators }}
  sourceNamespace: {{ .Values.srcnamespace }}"
