apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: {{ .Values.meshctrlplanens }}
spec:
  members:
   {{ range .Values }}
   - {{ .meshmemberroll }}
   {{ end }}
