apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "etherpad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "etherpad.selectorLabels" . | nindent 4 }}

# .Values to access anything in the values
# .Chart to access information about the chart (name, version, etc.)
# toYaml, which will convert an object to its raw YAML representation
# nindent, which ensures indentation level
# include, which allows you to include YAML sections predefined in _helpers.tpl
